spring.application.name=fraud
server.port=8081

# Secure Runtime Cloud Connection Setup
spring.datasource.url=jdbc:postgresql://ep-wispy-cake-aq708b9k-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Protects database schemas from structural drops
spring.jpa.hibernate.ddl-auto=validate
