spring.application.name=fraud
server.port=8081

# Secure Runtime Cloud Connection with String Escape Rules
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly defines the database language so Hibernate doesn't have to guess via metadata
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
